name: jangolo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  intl: ^0.19.0
  mobile_scanner: ^7.0.1
  flutter_riverpod: ^2.5.1
  flutter_speed_dial: ^7.0.0
  uuid: ^4.4.0 # ✅ <--- AJOUTEZ CETTE LIGNE

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true