// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuor0RHq6wLOgRwQIrsa0dLt8WGQb9j1s',
    appId: '1:370850548318:web:a2e9a20383f413132482cf',
    messagingSenderId: '370850548318',
    projectId: 'jangolo-89938',
    authDomain: 'jangolo-89938.firebaseapp.com',
    storageBucket: 'jangolo-89938.firebasestorage.app',
    measurementId: 'G-W2ZF66X350',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChHaTBzr8BUZzqhJbm3sU2KhM8Lxxs5DE',
    appId: '1:370850548318:android:96d8e459685c55cc2482cf',
    messagingSenderId: '370850548318',
    projectId: 'jangolo-89938',
    storageBucket: 'jangolo-89938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhIQFAqxklGdJgca2_CwnvGJjQkchNznM',
    appId: '1:370850548318:ios:4be3b6b37967c2492482cf',
    messagingSenderId: '370850548318',
    projectId: 'jangolo-89938',
    storageBucket: 'jangolo-89938.firebasestorage.app',
    iosBundleId: 'com.example.jangolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhIQFAqxklGdJgca2_CwnvGJjQkchNznM',
    appId: '1:370850548318:ios:4be3b6b37967c2492482cf',
    messagingSenderId: '370850548318',
    projectId: 'jangolo-89938',
    storageBucket: 'jangolo-89938.firebasestorage.app',
    iosBundleId: 'com.example.jangolo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuor0RHq6wLOgRwQIrsa0dLt8WGQb9j1s',
    appId: '1:370850548318:web:0c0993d7dda8410b2482cf',
    messagingSenderId: '370850548318',
    projectId: 'jangolo-89938',
    authDomain: 'jangolo-89938.firebaseapp.com',
    storageBucket: 'jangolo-89938.firebasestorage.app',
    measurementId: 'G-LV93QDG4YT',
  );
}
